#!/bin/bash
module load python
module load mpi4py
module load h5py-parallel
export PYTHONPATH=`pwd`/h5boss_py:$PYTHONPATH
export PATH=`pwd`/h5boss_py/scripts:$PATH
export basedir=/global/projecta/projectdirs/sdss/data/sdss/dr12/boss/spectro/redux/v5_7_0
