#!/usr/bin/env python
"""
Create an HDF5 file from BOSS data

TODO:
  - include comments in meta/attrs
  - platelist quantities
"""
from __future__ import division, print_function
#from __future__ import absolute_import
from h5boss.select import select
import sys,os
import time
import optparse
import csv
import traceback

parser = optparse.OptionParser(usage = "%prog [options]")
parser.add_option("-i", "--input", type=str,  help="input subselected file")
parser.add_option("-o", "--output", type=str,  help="output hdf5 file")
parser.add_option("-p", "--plate", type=str,  help="plates csv file")
parser.add_option("-m", "--mjd", type=str,  help="mjds csv file")
parser.add_option("-f", "--fiber", type=str,  help="fibers csv file")

opts, args = parser.parse_args()

platefile = opts.plate
mjdfile = opts.mjd
fiberfile = opts.fiber
infiles = opts.input
outfile = opts.output
tstart=time.time()
try: 
 with open(platefile, 'rb') as f:
  reader = csv.reader(f)
  plates = list(reader)

except Exception, e:
  print ("CSV file open error: %s "%e,plates)
  traceback.print_exc()

try:
 with open(mjdfile,'rb') as f:
  reader = csv.reader(f)
  mjds = list(reader)

except Exception, e:
 print ("CSV file open error: %s"%e,mjdfile)
 traceback.print_exc()

try:
 with open(fiberfile,'rb') as f:
  reader = csv.reader(f)
  fibers = list(reader)

except Exception, e:
 print ("CSV file open error: %s"%e,fiberfile)
 traceback.print_exc()


try:
 with open(infiles,'rb') as f:
  reader = csv.reader(f)
  infile = list(reader)

except Exception, e:
 print ("CSV file open error: %s"%e,infiles)
 traceback.print_exc()

infile = [x for sublist in infile for x in sublist]
fibers = [x for sublist in fibers for x in sublist]
plates = [x for sublist in plates for x in sublist]
mjds = [x for sublist in mjds for x in sublist]

print ("Plates: ",plates)
print ("MJDs: ",mjds)
print ("Fibers: ", fibers)
print ("Input: ",infile)
print ("Output: ", outfile)
print ("Run selecting...")

try:
 select(infile, outfile, plates, mjds, fibers)

except Exception, e:
 print ("Error in select:")
 traceback.print_exc()
print ("Done selection")
