#!/usr/bin/env python
"""
Create an HDF5 file from BOSS data

TODO:
  - include comments in meta/attrs
  - platelist quantities
"""
from __future__ import division, print_function
#from __future__ import absolute_import
from h5boss.select import select
import sys,os
import time
import optparse
import csv
import traceback


import optparse
import argparse
parser = argparse.ArgumentParser(prog='subset')
parser.add_argument("input",  help="HDF5 input list")
parser.add_argument("output", help="HDF5 output")
parser.add_argument("pmf",    help="Plate/mjd/fiber list in csv")

opts=parser.parse_args()


#parser = optparse.OptionParser(usage = "%prog [options]")
#parser.add_option("-i", "--input", type=str,  help="input file list")
#parser.add_option("-o", "--output", type=str,  help="output hdf5")
#parser.add_option("-x", "--xls", type=str,help="pmf excel")
#parser.add_option("-l", "--pmf",type=str,help="pmf csv")
#opts, args = parser.parse_args()

#xlsfile = opts.xls
pmflist = opts.pmf
infiles = opts.input
outfile = opts.output
tstart=time.time()
#import pandas as pd
#try: 
# df = pd.ExcelFile(xlsfile).parse('Sheet1')
# plates = map(str,df['plates'].values.tolist())
# mjds = map(str,df['mjds'].values.tolist())
# fibers = map(str,df['fibers'].values.tolist())

#except Exception, e:
# print("excel read error or not exist:%s"%e,xlsfile)
 #traceback.print_exc()

try:
 df = pd.read_csv(pmflist,delimiter=' ',names=["plates","mjds","fibers"],index_col=None,dtype=str)
 plates = map(str,df['plates'].values.tolist())
 mjds = map(str,df['mjds'].values.tolist())
 fibers = map(str,df['fibers'].values.tolist())
except Exception, e:
 print("pmf csv read error or not exist:%s"%e,pmflist)
 print("e.g., 1st row of csv should be 'plates mjds fibers'")

try:
 with open(infiles,'rb') as f:
  reader = csv.reader(f)
  infile = list(reader)

except Exception, e:
 print ("input csv read error or not exist: %s"%e,infiles)
 #traceback.print_exc()

infile = [x for sublist in infile for x in sublist]
#print ("Plates: ",plates)
#print ("MJDs: ",mjds)
#print ("Fibers: ", fibers)
if(len(plates)==0 or len(infile)==0):
  print("pmf or input is empty")
  sys.exit(0)

print ("Input: %d files:"%len(infile),infile[0],"...",infile[-1])
print ("Output: ", outfile)
print ("Running selection...")
try:
 select(infile, outfile, plates, mjds, fibers)

except Exception, e:
 print ("Error in select:")
 traceback.print_exc()
print ("Done selection")
